[project]
name = "cofy-api"
authors = [
    { name="EnergyID", email = "info@energieid.be" },
    { name="Jorg" }
]
version = "0.1.0"
description = "An open-source modular framework for ingesting, standardising, storing, and computing energy-related data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "entsoe-py>=0.7.10",
    "fastapi[standard]>=0.128.0",
    "narwhals>=2.15.0",
    "pandas>=3.0.0",
    "polars>=1.37.1",
]
[dependency-groups]
dev = [
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]
[tool.poe.tasks]
lint = "ruff check --fix"
format = "ruff format"
check = "ty check"
[tool.poe.tasks.demo]
cmd = "fastapi dev src/demo/main.py"
env = { PYTHONPATH = "." }
envfile = ".env.local"
[tool.poe.tasks.test]
cmd = "pytest --cov=src --cov-report=term-missing --import-mode=importlib"
env = { PYTHONPATH = "." }
[tool.coverage.report]
skip_covered = true
[tool.coverage.run]
omit = ["src/demo/*"]
[tool.ruff]
line-length = 200
[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]
ignore = [
    "E501", #Line too long
]
