[project]
name = "cofy-api"
authors = [
    { name="EnergyID", email = "info@energieid.be" },
    { name="Jorg" }
]
version = "0.1.0"
description = "An open-source modular framework for ingesting, standardising, storing, and computing energy-related data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]
[tool.poe.tasks.demo]
cmd = "fastapi dev src/demo/main.py"
env = { PYTHONPATH = "." }
[tool.poe.tasks]
lint = "ruff check"
format = "ruff format"
check = "ty check"
