[project]
name = "cofy-api"
authors = [
    { name="EnergyID", email = "info@energieid.be" },
    { name="Jorg" }
]
version = "0.1.0"
description = "An open-source modular framework for ingesting, standardising, storing, and computing energy-related data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
# Functional extras
api = ["fastapi[standard]>=0.128.0"]
worker = ["saq[postgres,web] @ git+https://github.com/tobymao/saq.git"]
db = [
    "psycopg[binary]>=3.3.3",
    "alembic>=1.18.4", 
    "sqlalchemy>=2.0.0"
]

# Module extras
timeseries = ["narwhals>=2.15.0"]
tariff = [
    "cofy-api[timeseries]",
    "entsoe-py>=0.7.10",
    "pandas>=3.0.0"
]
members = ["cofy-api[db]"]

# Convenience extras
all = ["cofy-api[api,worker,db,timeseries,tariff,members]"]

[dependency-groups]
dev = [
    "cofy-api[all]",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]
[tool.poe.tasks]
lint = "ruff check --fix"
format = "ruff format"
check = "ty check"
[tool.poe.tasks.demo]
cmd = "fastapi dev src/demo/main.py"
env = { PYTHONPATH = "." }
envfile = ".env.local"
[tool.poe.tasks.db]
cmd = "python -m src.demo.db"
envfile = ".env.local"
env = { PYTHONPATH = "." }
[tool.poe.tasks.worker]
cmd = "saq src.demo.worker.settings"
env = { PYTHONPATH = "." }
envfile = ".env.local"
[tool.poe.tasks.test]
cmd = "pytest --cov=src --cov-report=term-missing --import-mode=importlib"
env = { PYTHONPATH = "." }
[tool.coverage.report]
skip_covered = true
[tool.coverage.run]
source = ["src"]
omit = ["src/demo/*", "src/modules/*/migrations/*", "src/cofy/db/alembic/*"]
[tool.ruff]
line-length = 120
[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]
ignore = [
    "E501", #Line too long
]
