[project]
name = "cofy-api"
authors = [
    { name="EnergyID", email = "info@energieid.be" },
    { name="Jorg" }
]
version = "0.1.0"
description = "An open-source modular framework for ingesting, standardising, storing, and computing energy-related data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "entsoe-py>=0.7.10",
    "fastapi[standard]>=0.128.0",
    "narwhals>=2.15.0",
    "pandas>=3.0.0",
    "polars>=1.37.1",
    "saq>=0.26.1",
]
[dependency-groups]
dev = [
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]
[tool.poe.tasks]
lint = "ruff check --fix"
format = "ruff format"
check = "ty check"
[tool.poe.tasks.demo]
cmd = "fastapi dev src/demo/main.py"
env = { PYTHONPATH = "." }
envfile = ".env.local"
[tool.poe.tasks.db-seed]
cmd = "python -m src.demo.db.seed"
envfile = ".env.local"
env = { PYTHONPATH = "." }
[tool.poe.tasks.db-reset]
cmd = "python -m src.demo.db.reset"
envfile = ".env.local"
[tool.poe.tasks.db-migrate]
cmd = "python -m src.demo.db.migrate"
envfile = ".env.local"
env = { PYTHONPATH = "." }
[tool.poe.tasks.db-generate]
cmd = "python -m src.demo.db.generate"
envfile = ".env.local"
env = { PYTHONPATH = "." }
[tool.poe.tasks.worker]
cmd = "saq src.demo.worker.settings"
env = { PYTHONPATH = "." }
envfile = ".env.local"
[tool.poe.tasks.worker-web]
cmd = "saq src.demo.worker.settings --web"
env = { PYTHONPATH = "." }
envfile = ".env.local"
[tool.poe.tasks.test]
cmd = "pytest --cov=src --cov-report=term-missing --import-mode=importlib"
env = { PYTHONPATH = "." }
[tool.coverage.report]
skip_covered = true
[tool.coverage.run]
source = ["src"]
omit = ["src/demo/*", "src/modules/*/migrations/*", "src/cofy/db/alembic/*"]
[tool.ruff]
line-length = 120
[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]
ignore = [
    "E501", #Line too long
]
